# Generated by Django 3.2.21 on 2023-09-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkItem',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('drink_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField()),
                ('drink_type', models.IntegerField(choices=[(0, 'Beers'), (1, 'Wines'), (2, 'Cocktails')])),
            ],
            options={
                'ordering': ['-drink_type'],
            },
        ),
        migrations.CreateModel(
            name='TapasItem',
            fields=[
                ('tapas_id', models.AutoField(primary_key=True, serialize=False)),
                ('tapas_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tapas_price', models.FloatField(default=0)),
                ('plato_price', models.FloatField(default=0)),
                ('sides_price', models.FloatField(default=0)),
                ('tapas_type', models.IntegerField(choices=[(0, 'Salads & Cold Cuts'), (1, 'Hot Dishes'), (2, 'Sides')])),
            ],
            options={
                'ordering': ['-tapas_type'],
            },
        ),
    ]
