# Generated by Django 3.2.21 on 2023-09-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapasitem',
            name='sides_price',
            field=models.FloatField(default=''),
        ),
    ]
