# Generated by Django 3.2.21 on 2023-09-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_tapasitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapasitem',
            name='dessert_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='drink_type',
            field=models.IntegerField(choices=[(0, 'Beers & Ciders'), (1, 'Wines'), (2, 'Cocktails'), (3, 'Spirits')]),
        ),
        migrations.AlterField(
            model_name='tapasitem',
            name='tapas_type',
            field=models.IntegerField(choices=[(0, 'Salads & Cold Cuts'), (1, 'Hot Dishes'), (2, 'Sides'), (3, 'Desserts')]),
        ),
    ]
