# Generated by Django 3.2.21 on 2023-09-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_tapasitem_sides_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapasitem',
            name='sides_price',
            field=models.FloatField(default='2'),
        ),
    ]
