# Generated by Django 3.2.21 on 2023-09-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20230924_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkitem',
            name='bottle_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drinkitem',
            name='glass_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='drink_type',
            field=models.IntegerField(choices=[(0, 'Beers & Ciders'), (1, 'Wines & Sparkling'), (2, 'Cocktails'), (3, 'Spirits')]),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
