# Generated by Django 3.2.21 on 2023-09-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20230924_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkitem',
            old_name='price',
            new_name='drink_price',
        ),
    ]
