# Generated by Django 3.2.21 on 2023-09-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_remove_tapasitem_sides_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapasitem',
            name='sides_price',
            field=models.FloatField(default=0),
        ),
    ]
