# Generated by Django 3.2.21 on 2023-09-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_tapasitem_sides_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapasitem',
            name='description',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tapasitem',
            name='plato_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tapasitem',
            name='sides_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tapasitem',
            name='tapas_price',
            field=models.FloatField(blank=True),
        ),
    ]
