# Generated by Django 3.2.21 on 2023-09-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20230916_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapasitem',
            name='plato_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tapasitem',
            name='tapas_price',
            field=models.FloatField(default=0),
        ),
    ]
