# Generated by Django 3.2.21 on 2023-09-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_auto_20230916_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkItem',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('drink_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('drink_type', models.IntegerField(choices=[(0, 'Beers'), (1, 'Wines'), (2, 'Cocktails')])),
            ],
            options={
                'ordering': ['-drink_type'],
            },
        ),
        migrations.AlterField(
            model_name='tapasitem',
            name='sides_price',
            field=models.FloatField(default=0),
        ),
    ]
